spring:
  application:
    name: yagoomap
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}  # 로컬: redis://, Upstash: rediss://
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
